const recipe_data = [
    { recipeID: 0, recipeName: 'Curry', serving: 4, ingredients: [('Japanese rice', '2 cups'), 
    ('water', '4 cups'), ('onion', '1'), ('carrot', '2'), ('potatoe', '2'), ('chicken', '1 lb'), 
    ('vegetable oil', '2 tbsp'), ('Japanese curry roux', '1 box (8.4 oz.)'), ('Salt and pepper', 'some')],  
    instructions: ['Rinse the rice in a strainer and let it soak in water for 30 minutes.', 
    'In a large pot, heat the vegetable oil over medium heat. Add the chopped onions and cook until they are translucent.', 
    'Add the chicken or beef to the pot and cook until it\'s no longer pink.', 
    'Add the chopped carrots and potatoes to the pot and cook for a few minutes until they start to soften.', 
    'Add 4 cups of water to the pot and bring it to a boil.', 
    'Turn the heat down to low and simmer for about 20 minutes until the vegetables are fully cooked.', 
    'Add the curry roux to the pot and stir until it dissolves. Simmer for another 10 minutes until the curry thickens.', 
    'Season with salt and pepper to taste.', 
    'To make the rice, drain the water from the rice and put it in a rice cooker with 2 cups of water. Cook according to the manufacturer\'s instructions.', 
    'Serve the curry over the rice and enjoy!']},
    { recipeID: 1, recipeName: 'Saucy bean baked eggs', serving: 2, ingredients: [('cherry tomatoes', '2 x 400g cans'), 
    ('mixed bean salad', '400g can'), ('baby spinach', '200g'), ('egg', '4'), ('ham', '50g')],  
    instructions: ['Tip the tomatoes and bean salad into an ovenproof frying pan or shallow flameproof casserole dish. Simmer for 10 mins, or until reduced. Stir in the spinach and cook for 5 mins more until wilted.', 
    'Heat the grill to medium. Make four indentations in the mixture using the back of a spoon, then crack one egg in each. Nestle the ham in the mixture, then grill for 4-5 mins, or until the whites are set and the yolks runny. Serve with rye bread, if you like.']}, 
    { recipeID: 2, recipeName: 'Healthy banana bread', serving: 2, ingredients: [('spread', 'some'), 
    ('wholemeal flour', '140g'), ('self-raising flour', '100g'), ('bicarbonate of soda', '1 tsp'), ('baking powder', '1 tsp'), 
    ('banana', '300g'), ('agave syrup', '4 tsp'), ('egg', '3'), ('yogurt', '150ml')],  
    instructions: ['Heat oven to 160C/140C fan/gas 3. Grease and line a 2lb loaf tin with baking parchment (allow it to come 2cm above top of tin). Mix the flours, bicarb, baking powder and a pinch of salt in a large bowl.', 
    'Mix the bananas, syrup, eggs and yogurt. Quickly stir into dry ingredients, then gently scrape into the tin and scatter with nuts, if using. Bake for 1 hr 10 mins-1 hr 15 mins or until a skewer comes out clean.', 
    'Cool in tin on a wire rack. Eat warm or at room temperature, with low-fat spread.']}, 
    { recipeID: 3, recipeName: 'Thai Coconut Soup', serving: 8, ingredients: [('vegetable oil', '1 tbsp'), 
    ('grated fresh ginger', '2 tbsp'), ('red curry paste', '2 tsp'), ('lemon grass', '1 stalk'), ('chicken broth', '4 cups'), 
    ('fish sauce', '3 tbsp'), ('brown sugar', '3 tbsp'), ('coconut milk', '3 cans'), ('mushroom', '1/2 pound'), 
    ('shrimp', '1 pound'), ('lime juice', '2 tbsp'), ('salt', 'some'), ('cilantro', '1/4 cup')],  
    instructions: ['Heat oil in a large pot over medium heat. Add ginger, curry paste, and lemongrass; cook and stir in the hot oil for 1 minute.', 
    'Gradually stir in chicken broth, then stir in fish sauce and brown sugar; reduce heat to low and simmer for 15 minutes.', 
    'Add coconut milk and mushrooms; cook and stir until mushrooms are soft, about 5 minutes.', 
    'Add shrimp; cook until no longer translucent, about 5 minutes. Stir in lime juice; season with salt and garnish with cilantro.']}, 
    { recipeID: 4, recipeName: 'Onion Chicken', serving: 4, ingredients: [('butter', '1/2 cup'), 
    ('Worcestershire sauce', '1 tbsp'), ('ground mustard', '1 tsp'), ('onion', '1'), ('chicken', '16 ounces')],  
    instructions: ['In a shallow bowl, combine butter, Worcestershire sauce and mustard. Place onions in another shallow bowl. Dip chicken in butter mixture, then coat with onions.', 
    'Place in a greased 11x7-in. baking dish; drizzle with remaining butter mixture. Bake, uncovered, at 400° for 20-25 minutes or until a thermometer reads 165°.']}, 
    { recipeID: 5, recipeName: 'Marinated Grilled Flank Steak', serving: 8, ingredients: [('barbecue sauce', '1 cup'), 
    ('beef broth', '1/2 cup'), ('lemon juice', '1/4 cup'), ('beef flank steak', '2 pounds')],  
    instructions: ['In a small bowl, whisk barbecue sauce, wine and lemon juice until blended. Pour 1 cup marinade into a shallow dish. Add beef and turn to coat. Cover; refrigerate 4 hours or overnight. Cover and refrigerate remaining marinade.', 
    'Drain beef, discarding marinade in dish. Grill steak, covered, over medium heat until meat reaches desired doneness (for medium-rare, a thermometer should read 135°; medium, 140°; medium-well, 145°), 6-8 minutes on each side. Let stand 5 minutes before thinly slicing across the grain. Serve with reserved marinade.']}, 
    { recipeID: 6, recipeName: 'Chicken with Rosemary Butter Sauce', serving: 4, ingredients: [('chicken', '24 ounces'), 
    ('butter', '4 tbsp'), ('chicken broth', '1/2 cup'), ('cream', '1/2 cup'), ('rosemary', '1 tbsp')],  
    instructions: ['In a large skillet over medium heat, cook chicken in 1 tablespoon butter until a thermometer reads 165°, 4-5 minutes on each side. Remove and keep warm.', 
    'Add wine to pan; cook over medium-low heat, stirring to loosen browned bits from pan. Add cream and bring to a boil. Reduce heat; cook and stir until slightly thickened. Stir in rosemary and remaining 3 tablespoons butter until blended. Serve sauce with chicken.']}, 
    { recipeID: 7, recipeName: 'Breaded Pork Chops', serving: 6, ingredients: [('egg', '1'), 
    ('milk', '1/2 cup'), ('cracker', '1/2 cup'), ('pork loin chops', '6'), ('canola oil', '1/4 cup')],  
    instructions: ['In a shallow bowl, combine egg and milk. Place cracker crumbs in another shallow bowl. Dip each pork chop in egg mixture, then coat with cracker crumbs, patting to make a thick coating.', 
    'In a large skillet, cook chops in oil for 4-5 minutes on each side or until a thermometer reads 145°. Let meat stand for 5 minutes before serving.']}, 
    { recipeID: 8, recipeName: 'Baked Fish', serving: 4, ingredients: [('fish fillet', '1/4 pounds'), 
    ('salt', '1 tsp'), ('pepper', 'some'), ('butter', '3 tbsp')],  
    instructions: ['Preheat oven to 400°. Place fish in a greased 11x7-in. baking dish. Sprinkle with seasoned salt, pepper and, if desired, paprika. Drizzle with butter.', 
    'Cover and bake until fish just begins to flake easily with a fork, 15-20 minutes.']}, 
    { recipeID: 9, recipeName: 'Fruited Pot Roast', serving: 6, ingredients: [('dried fruit', '7 ounces'), 
    ('onion', '1'), ('apple juice', '1 can'), ('beef', '2 pounds'), ('salt', '1/2 tsp'), ('allspice', '1/4 tsp'), ('pepper', '1/4 tsp')],  
    instructions: ['Place fruit and onion in a 3- or 4-qt. slow cooker; add apple juice. Top with roast; sprinkle with seasonings.', 
    'Cover and cook on low until meat is tender, 6-8 hours. Serve beef with fruit mixture.']}, 
    { recipeID: 10, recipeName: 'Nutty Cheese Tortellini', serving: 3, ingredients: [('tortellini', '9 ounces'), 
    ('butter', '1/2 cup'), ('parsley', '1/2 cup'), ('walnut', '1/3 cup'), ('Parmesan cheese', '1/4 cup'), ('pepper', 'some')],  
    instructions: ['Cook tortellini according to package directions; drain and keep warm. In the same pan, melt butter. Stir in the tortellini, parsley and walnuts; toss to coat. Sprinkle with cheese and pepper.']}, 
    { recipeID: 11, recipeName: 'Sausage Hash', serving: 6, ingredients: [('sausage', '1 pound'), 
    ('onion', '1'), ('carrot', '2'), ('green pepper', '1'), ('potato', '3'), ('salt', '1/2 tsp'), ('pepper', '1/4 tsp')],  
    instructions: ['In a large cast-iron or other heavy skillet, cook the sausage over medium heat until no longer pink; drain. Add the onion, carrots and green pepper; cook until tender. Stir in the potatoes, salt and pepper. Reduce heat; cook and stir until lightly browned and heated through, about 20 minutes.']}, 
    { recipeID: 12, recipeName: 'Ravioli Lasagna', serving: 8, ingredients: [('beef', '1 pound'), 
    ('spaghetti sauce', '1 jar'), ('sausage', '25 ounces'), ('mozzarella cheese', '1/2 cup')],  
    instructions: ['In a large skillet, cook and crumble beef over medium heat until no longer pink, 5-7 minutes; drain. In a greased 2-1/2-qt. baking dish, layer a third of the spaghetti sauce, half of the ravioli and beef, and 1/2 cup cheese; repeat layers. Top with remaining sauce and cheese.', 
    'Cover and bake at 400° until heated through, 40-45 minutes. If desired, top with basil to serve.']}, 
    { recipeID: 13, recipeName: 'Cheeseburger French Fry Casserole', serving: 8, ingredients: [('beef', '2 pounds'), 
    ('condensed golden mushroom soup', '1 can'), ('condensed cheddar cheese soup', '1 can'), ('french fries', '20 ounces')],  
    instructions: ['Preheat oven to 350°. In a large skillet, cook beef over medium heat until no longer pink; drain. Stir in soups. Pour into a greased 13x9-in. baking dish.', 
    'Arrange french fries on top. Bake, uncovered, until the fries are golden brown, 50-55 minutes.']}, 
    { recipeID: 14, recipeName: 'Grilled Peppered Steaks', serving: 4, ingredients: [('pepper', '2 tsp'), 
    ('onion salt', '1 tsp'), ('garlic salt', '1 tsp'), ('beef loin steaks', '32 ounces')],  
    instructions: ['In a small bowl, combine the pepper, onion salt, garlic salt and, if desired, paprika. Rub onto both sides of steaks.', 
    'Grill, covered, over medium heat until meat reaches desired doneness (for medium-rare, a thermometer should read 135°; medium, 140°; medium-well, 145°), 8-10 minutes on each side.']}
]


