const recipe_data = [
    { recipeID: 0, recipeName: 'Curry', serving: 4, ingredients: [['Japanese rice', '2 cups'],
    ['water', '4 cups'], ['onion', '1'], ['carrot', '2'], ['potatoe', '2'], ['chicken', '1 lb'],
    ['vegetable oil', '2 tbsp'], ['Japanese curry roux', '1 box (8.4 oz.)'], ['Salt and pepper', 'some']],
    instructions: ['Rinse the rice in a strainer and let it soak in water for 30 minutes.',
    'In a large pot, heat the vegetable oil over medium heat. Add the chopped onions and cook until they are translucent.',
    'Add the chicken or beef to the pot and cook until it\'s no longer pink.',
    'Add the chopped carrots and potatoes to the pot and cook for a few minutes until they start to soften.',
    'Add 4 cups of water to the pot and bring it to a boil.',
    'Turn the heat down to low and simmer for about 20 minutes until the vegetables are fully cooked.',
    'Add the curry roux to the pot and stir until it dissolves. Simmer for another 10 minutes until the curry thickens.',
    'Season with salt and pepper to taste.',
    'To make the rice, drain the water from the rice and put it in a rice cooker with 2 cups of water. Cook according to the manufacturer\'s instructions.',
    'Serve the curry over the rice and enjoy!'],
    image_link: 'https://sudachirecipes.com/wp-content/uploads/2022/08/beef-curry-rice-thumbnail.jpg'},
    { recipeID: 1, recipeName: 'Saucy bean baked eggs', serving: 2, ingredients: [['cherry tomatoes', '2 x 400g cans'],
    ['mixed bean salad', '400g can'], ['baby spinach', '200g'], ['egg', '4'], ['ham', '50g']],
    instructions: ['Tip the tomatoes and bean salad into an ovenproof frying pan or shallow flameproof casserole dish. Simmer for 10 mins, or until reduced. Stir in the spinach and cook for 5 mins more until wilted.',
    'Heat the grill to medium. Make four indentations in the mixture using the back of a spoon, then crack one egg in each. Nestle the ham in the mixture, then grill for 4-5 mins, or until the whites are set and the yolks runny. Serve with rye bread, if you like.'],
    image_link:'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/saucy-bean-baked-eggs-d582e18.jpg?quality=90&webp=true&resize=440,400'},
    { recipeID: 2, recipeName: 'Healthy banana bread', serving: 2, ingredients: [['spread', 'some'],
    ['wholemeal flour', '140g'], ['self-raising flour', '100g'], ['bicarbonate of soda', '1 tsp'], ['baking powder', '1 tsp'],
    ['banana', '300g'], ['agave syrup', '4 tsp'], ['egg', '3'], ['yogurt', '150ml']],
    instructions: ['Heat oven to 160C/140C fan/gas 3. Grease and line a 2lb loaf tin with baking parchment (allow it to come 2cm above top of tin). Mix the flours, bicarb, baking powder and a pinch of salt in a large bowl.',
    'Mix the bananas, syrup, eggs and yogurt. Quickly stir into dry ingredients, then gently scrape into the tin and scatter with nuts, if using. Bake for 1 hr 10 mins-1 hr 15 mins or until a skewer comes out clean.',
    'Cool in tin on a wire rack. Eat warm or at room temperature, with low-fat spread.'],
    image_link:'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-1095472_12-ae71956.jpg?quality=90&webp=true&resize=440,400'},
    { recipeID: 3, recipeName: 'Thai Coconut Soup', serving: 8, ingredients: [['vegetable oil', '1 tbsp'],
    ['grated fresh ginger', '2 tbsp'], ['red curry paste', '2 tsp'], ['lemon grass', '1 stalk'], ['chicken broth', '4 cups'],
    ['fish sauce', '3 tbsp'], ['brown sugar', '3 tbsp'], ['coconut milk', '3 cans'], ['mushroom', '1/2 pound'],
    ['shrimp', '1 pound'], ['lime juice', '2 tbsp'], ['salt', 'some'], ['cilantro', '1/4 cup']],
    instructions: ['Heat oil in a large pot over medium heat. Add ginger, curry paste, and lemongrass; cook and stir in the hot oil for 1 minute.',
    'Gradually stir in chicken broth, then stir in fish sauce and brown sugar; reduce heat to low and simmer for 15 minutes.',
    'Add coconut milk and mushrooms; cook and stir until mushrooms are soft, about 5 minutes.',
    'Add shrimp; cook until no longer translucent, about 5 minutes. Stir in lime juice; season with salt and garnish with cilantro.'],
    image_link:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fpublic-assets.meredithcorp.io%2F0b2b0ae0fc2ce82256e7c7e5c4399fc0%2F1675116004180F69959BC-5FD9-4D3E-B26D-099E11C19E60.jpeg&q=60&c=sc&orient=true&poi=auto&h=512'},
    { recipeID: 4, recipeName: 'Onion Chicken', serving: 4, ingredients: [['butter', '1/2 cup'],
    ['Worcestershire sauce', '1 tbsp'], ['ground mustard', '1 tsp'], ['onion', '1'], ['chicken', '16 ounces']],
    instructions: ['In a shallow bowl, combine butter, Worcestershire sauce and mustard. Place onions in another shallow bowl. Dip chicken in butter mixture, then coat with onions.',
    'Place in a greased 11x7-in. baking dish; drizzle with remaining butter mixture. Bake, uncovered, at 400° for 20-25 minutes or until a thermometer reads 165°.'],
    image_link:'https://www.eatingwell.com/thmb/awUOmJ528TxRnPui8ox_wVC3vnw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/skilletsourcreamandonionchicken-rm-0397-1464de60211d44729f6439933108fdbd.jpg'},
    { recipeID: 5, recipeName: 'Marinated Grilled Flank Steak', serving: 8, ingredients: [['barbecue sauce', '1 cup'],
    ['beef broth', '1/2 cup'], ['lemon juice', '1/4 cup'], ['beef flank steak', '2 pounds']],
    instructions: ['In a small bowl, whisk barbecue sauce, wine and lemon juice until blended. Pour 1 cup marinade into a shallow dish. Add beef and turn to coat. Cover; refrigerate 4 hours or overnight. Cover and refrigerate remaining marinade.',
    'Drain beef, discarding marinade in dish. Grill steak, covered, over medium heat until meat reaches desired doneness (for medium-rare, a thermometer should read 135°; medium, 140°; medium-well, 145°), 6-8 minutes on each side. Let stand 5 minutes before thinly slicing across the grain. Serve with reserved marinade.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Easy-Marinated-Grilled-Flank-Steak_EXPS_FTTMZ19_32073_C03_05_5b_rms-5.jpg?fit=700,1024'},
    { recipeID: 6, recipeName: 'Chicken with Rosemary Butter Sauce', serving: 4, ingredients: [['chicken', '24 ounces'],
    ['butter', '4 tbsp'], ['chicken broth', '1/2 cup'], ['cream', '1/2 cup'], ['rosemary', '1 tbsp']],
    instructions: ['In a large skillet over medium heat, cook chicken in 1 tablespoon butter until a thermometer reads 165°, 4-5 minutes on each side. Remove and keep warm.',
    'Add wine to pan; cook over medium-low heat, stirring to loosen browned bits from pan. Add cream and bring to a boil. Reduce heat; cook and stir until slightly thickened. Stir in rosemary and remaining 3 tablespoons butter until blended. Serve sauce with chicken.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Chicken-with-Rosemary-Butter-Sauce_EXPS_FT20_44349_F_0123_1-6.jpg?fit=700,1024'},
    { recipeID: 7, recipeName: 'Breaded Pork Chops', serving: 6, ingredients: [['egg', '1'],
    ['milk', '1/2 cup'], ['cracker', '1/2 cup'], ['pork loin chops', '6'], ['canola oil', '1/4 cup']],
    instructions: ['In a shallow bowl, combine egg and milk. Place cracker crumbs in another shallow bowl. Dip each pork chop in egg mixture, then coat with cracker crumbs, patting to make a thick coating.',
    'In a large skillet, cook chops in oil for 4-5 minutes on each side or until a thermometer reads 145°. Let meat stand for 5 minutes before serving.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Breaded-Pork-Chops_EXPS_FT19_73_F_0820_1-13.jpg?fit=700,1024'},
    { recipeID: 8, recipeName: 'Baked Fish', serving: 4, ingredients: [['fish fillet', '1/4 pounds'],
    ['salt', '1 tsp'], ['pepper', 'some'], ['butter', '3 tbsp']],
    instructions: ['Preheat oven to 400°. Place fish in a greased 11x7-in. baking dish. Sprinkle with seasoned salt, pepper and, if desired, paprika. Drizzle with butter.',
    'Cover and bake until fish just begins to flake easily with a fork, 15-20 minutes.'],
    image_link: 'https://img.taste.com.au/SMCVKSjB/taste/2018/08/creamy-lemon-salmon-tray-bake-139865-2.jpg'},
    { recipeID: 9, recipeName: 'Fruited Pot Roast', serving: 6, ingredients: [['dried fruit', '7 ounces'],
    ['onion', '1'], ['apple juice', '1 can'], ['beef', '2 pounds'], ['salt', '1/2 tsp'], ['allspice', '1/4 tsp'], ['pepper', '1/4 tsp']],
    instructions: ['Place fruit and onion in a 3- or 4-qt. slow cooker; add apple juice. Top with roast; sprinkle with seasonings.',
    'Cover and cook on low until meat is tender, 6-8 hours. Serve beef with fruit mixture.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/EXPS_HSCBZ19_45202_B07_3b-1.jpg?fit=700,1024'},
    { recipeID: 10, recipeName: 'Nutty Cheese Tortellini', serving: 3, ingredients: [['tortellini', '9 ounces'],
    ['butter', '1/2 cup'], ['parsley', '1/2 cup'], ['walnut', '1/3 cup'], ['Parmesan cheese', '1/4 cup'], ['pepper', 'some']],
    instructions: ['Cook tortellini according to package directions; drain and keep warm. In the same pan, melt butter. Stir in the tortellini, parsley and walnuts; toss to coat. Sprinkle with cheese and pepper.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Nutty-Cheese-Tortellini_EXPS_SDAM19_33978_C12_12_8b-1.jpg?fit=700,1024'},
    { recipeID: 11, recipeName: 'Sausage Hash', serving: 6, ingredients: [['sausage', '1 pound'],
    ['onion', '1'], ['carrot', '2'], ['green pepper', '1'], ['potato', '3'], ['salt', '1/2 tsp'], ['pepper', '1/4 tsp']],
    instructions: ['In a large cast-iron or other heavy skillet, cook the sausage over medium heat until no longer pink; drain. Add the onion, carrots and green pepper; cook until tender. Stir in the potatoes, salt and pepper. Reduce heat; cook and stir until lightly browned and heated through, about 20 minutes.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Sausage-Hash_EXPS_BMZ19_8404_C11_30_6b-15.jpg?fit=700,1024'},
    { recipeID: 12, recipeName: 'Ravioli Lasagna', serving: 8, ingredients: [['beef', '1 pound'],
    ['spaghetti sauce', '1 jar'], ['sausage', '25 ounces'], ['mozzarella cheese', '1/2 cup']],
    instructions: ['In a large skillet, cook and crumble beef over medium heat until no longer pink, 5-7 minutes; drain. In a greased 2-1/2-qt. baking dish, layer a third of the spaghetti sauce, half of the ravioli and beef, and 1/2 cup cheese; repeat layers. Top with remaining sauce and cheese.',
    'Cover and bake at 400° until heated through, 40-45 minutes. If desired, top with basil to serve.'],
    image_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/ravioli-lasagne-ff62ed4.jpg'},
    { recipeID: 13, recipeName: 'Cheeseburger French Fry Casserole', serving: 8, ingredients: [['beef', '2 pounds'],
    ['condensed golden mushroom soup', '1 can'], ['condensed cheddar cheese soup', '1 can'], ['french fries', '20 ounces']],
    instructions: ['Preheat oven to 350°. In a large skillet, cook beef over medium heat until no longer pink; drain. Stir in soups. Pour into a greased 13x9-in. baking dish.',
    'Arrange french fries on top. Bake, uncovered, until the fries are golden brown, 50-55 minutes.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Cheeseburger-n-Fries-Casserole_EXPS_13X9BZ19_7899_E10_05_6b-2.jpg?fit=700,1024'},
    { recipeID: 14, recipeName: 'Grilled Peppered Steaks', serving: 4, ingredients: [['pepper', '2 tsp'],
    ['onion salt', '1 tsp'], ['garlic salt', '1 tsp'], ['beef loin steaks', '32 ounces']],
    instructions: ['In a small bowl, combine the pepper, onion salt, garlic salt and, if desired, paprika. Rub onto both sides of steaks.',
    'Grill, covered, over medium heat until meat reaches desired doneness (for medium-rare, a thermometer should read 135°; medium, 140°; medium-well, 145°), 8-10 minutes on each side.'],
    image_link: 'https://www.tasteofhome.com/wp-content/uploads/2018/01/Grilled-Peppered-Steaks_EXPS_SDJJ19_23980_B02_07_3b-2.jpg?fit=700,1024'},
    {recipeID: 15,recipeName: 'Thai Style Spicy Chicken',serving: 2,ingredients: [['boneless chicken thighs','4'],['Salt','1/2 tsp'],['Freshly cracked sichuan peppercorn','1/2 tsp'],['Freshly cracked black pepper','1/2 tsp'],['onion thin strips','1'],['freshly cracked sichuan peppercorn','1 tsp'],['garlic minced','5 - 6 cloves'],['cilantro finely minced','2tbsp'],['thai chili seeded and minced','1'],['fish sauce','1 tbsp'],['sugar','1 tbsp'],['lemon juice','1/2']],instructions: ['Sprinkle salt, pepper, and sichuan pepper evenly on the boneless chicken thigh to season the meat for about 10 minutes.','Shred the onion into very thin slices and soak in ice water for about 10 mins and drain','When the skin is golden and crispy, flip over the thigh meat and fry for another 3 minutes to sear the meat.','Add 2 tsp hot oil from the pan to the bowl with minced garlic, Sichuan pepper, chilli, and cilantro to slightly saute these spices to bring out the aroma. Then mix the rest of the [Dressing] ingredients. Slightly adjust the taste to your preference.','Place some shredded onion and sliced crispy chicken on the plate. Then pour the sauce on top. Ready to serve!!'],image_link: 'https://farm1.staticflickr.com/458/20241785060_415d560b2c_z.jpg'},
    {
        recipeID: 16,
        recipeName: 'Roast Chicken',
        serving: 4,
        ingredients: [
          ['whole chicken', '1 (about 4 pounds)'],
          ['lemon', '1'],
          ['garlic', '1 head'],
          ['olive oil', '2 tablespoons'],
          ['salt', '1 teaspoon'],
          ['black pepper', '1/2 teaspoon'],
        ],
        instructions: [
          'Preheat oven to 425°F. Rinse chicken and pat dry.',
          'Cut lemon into quarters and place inside the chicken cavity along with garlic cloves.',
          'Place chicken in a roasting pan and brush with olive oil. Sprinkle with salt and pepper.',
          'Roast in the oven for 1 hour and 20 minutes, or until the internal temperature of the thickest part of the chicken reaches 165°F.',
          'Let chicken rest for 10-15 minutes before carving and serving.'
        ],
        image_link: 'https://www.allrecipes.com/thmb/ZNARl52mibyF1XHwwIb5A1czmkY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/83557-juicy-roast-chicken-mfs495-1-3d0f1e3e54104d43b24d4b480d2839ba.jpg'
      },
      {
        recipeID: 17,
        recipeName: 'Spaghetti Bolognese',
        serving: 4,
        ingredients: [
          ['spaghetti', '1 pound'],
          ['ground beef', '1 pound'],
          ['onion', '1'],
          ['garlic', '3 cloves'],
          ['canned tomatoes', '1 can (28 ounces)'],
          ['tomato paste', '2 tablespoons'],
          ['red wine', '1/2 cup'],
          ['dried oregano', '1 teaspoon'],
          ['dried basil', '1 teaspoon'],
          ['salt', '1 teaspoon'],
          ['black pepper', '1/2 teaspoon'],
          ['olive oil', '2 tablespoons']
        ],
        instructions: [
          'Cook spaghetti according to package instructions and set aside.',
          'In a large pot or Dutch oven, heat olive oil over medium-high heat. Add chopped onions and cook until they are translucent.',
          'Add minced garlic and cook for another minute.',
          'Add ground beef and cook until browned.',
          'Stir in canned tomatoes, tomato paste, red wine, dried oregano, dried basil, salt, and black pepper.',
          'Simmer for 30-45 minutes, stirring occasionally.',
          'Serve the sauce over cooked spaghetti.'
        ],
        image_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/the-best-spaghetti-bolognese-7e83155.jpg?quality=90&webp=true&resize=440,400'
      },
      {
        recipeID: 18,
        recipeName: 'Fish Tacos',
        serving: 4,
        ingredients: [
            ['tilapia fillets', '1 pound'],
            ['taco seasoning', '2 tablespoons'],
            ['lime juice', '2 tablespoons'],
            ['olive oil', '2 tablespoons'],
            ['tortillas', '8'],
            ['shredded cabbage', '2 cups'],
            ['sour cream', '1/2 cup'],
            ['hot sauce', 'to taste']
        ],
        instructions: [
            'Season tilapia fillets with taco seasoning and lime juice.',
            'Heat olive oil in a large skillet over medium-high heat. Add the seasoned tilapia and cook until golden brown and cooked through, about 3-4 minutes per side.',
            'Warm the tortillas in the microwave or on a skillet.',
            'Assemble the tacos with cooked tilapia, shredded cabbage, a dollop of sour cream, and hot sauce to taste.'
        ],
        image_link: 'https://www.simplyrecipes.com/thmb/s26SBzKQnBUTBXXot8o68wYBcso=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2004__06__Fish-Tacos-LEAD-6-321ec7a914744339941b6e184ee11fb8.jpg'
    },
    {
        recipeID: 19,
        recipeName: 'Chicken Caesar Salad',
        serving: 4,
        ingredients: [
            ['romaine lettuce', '1 head'],
            ['cooked chicken breast', '2'],
            ['grated Parmesan cheese', '1/2 cup'],
            ['croutons', '1 cup'],
            ['Caesar dressing', '1/2 cup'],
            ['lemon', '1'],
            ['olive oil', '2 tablespoons'],
            ['salt', '1/4 teaspoon'],
            ['black pepper', '1/4 teaspoon']
        ],
        instructions: [
            'Tear the romaine lettuce into bite-sized pieces and place in a large bowl.',
            'Slice the cooked chicken breast and add to the bowl.',
            'Add grated Parmesan cheese and croutons to the bowl.',
            'In a small bowl, whisk together Caesar dressing, lemon juice, olive oil, salt, and black pepper.',
            'Drizzle the dressing over the salad and toss to combine.'
        ],
        image_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/caesar-salad-7a44316.jpg?quality=90&webp=true&resize=440,400'
    },
    {
        recipeID: 20,
        recipeName: 'Beef Stroganoff',
        serving: 4,
        ingredients: [
            ['beef sirloin', '1 pound'],
            ['egg noodles', '8 ounces'],
            ['sour cream', '1/2 cup'],
            ['onion', '1'],
            ['garlic', '3 cloves'],
            ['beef broth', '1 cup'],
            ['flour', '2 tablespoons'],
            ['butter', '2 tablespoons'],
            ['olive oil', '2 tablespoons'],
            ['salt', '1 teaspoon'],
            ['black pepper', '1/2 teaspoon'],
            ['paprika', '1 teaspoon']
        ],
        instructions: [
            'Slice the beef sirloin into thin strips and season with salt, black pepper, and paprika.',
            'Cook egg noodles according to package instructions.',
            'In a large skillet, heat butter and olive oil over medium-high heat. Add the sliced onions and minced garlic and cook until the onions are translucent, about 5 minutes.',
            'Add the seasoned beef sirloin and cook until browned, about 5 minutes.',
            'Sprinkle flour over the beef and stir to coat. Cook for 1 minute.',
            'Add beef broth to the skillet and stir to combine. Bring to a simmer and cook until the sauce thickens, about 5 minutes.',
            'Remove the skillet from heat and stir in sour cream.',
            'Serve the beef stroganoff over cooked egg noodles.'
        ],
        image_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/beefstroganoff-d53f55e.jpg?quality=90&webp=true&resize=440,400'
    },
    {
        recipeID: 21,
        recipeName: 'Chicken Alfredo Pasta',
        serving: 4,
        ingredients: [
            ['penne pasta', '12 ounces'],
            ['chicken breast', '2'],
            ['heavy cream', '1 cup'],
            ['Parmesan cheese', '1/2 cup'],
            ['garlic', '3 cloves'],
            ['butter', '2 tablespoons'],
            ['olive oil', '2 tablespoons'],
            ['salt', '1 teaspoon'],
            ['black pepper', '1/2 teaspoon'],
            ['fresh parsley', 'for garnish']
        ],
        instructions: [
            'Cook penne pasta according to package instructions.',
            'Slice the chicken breast into bite-sized pieces and season with salt and black pepper.',
            'In a large skillet, heat butter and olive oil over medium-high heat. Add minced garlic and cook until fragrant, about 1 minute.',
            'Add seasoned chicken breast and cook until golden brown and cooked through, about 5-7 minutes.',
            'Reduce heat to low and add heavy cream and Parmesan cheese. Stir to combine and cook until the sauce thickens, about 5 minutes.',
            'Add cooked penne pasta to the skillet and toss to coat with the sauce.',
            'Garnish with fresh parsley and serve.'
        ],
        image_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chicken-alfredo-76fc36f.jpg?quality=90&webp=true&resize=440,400'
    },
    {
        recipeID: 22,
        recipeName: 'Vegetable Stir-Fry',
        serving: 4,
        ingredients: [
            ['broccoli florets', '2 cups'],
            ['carrots', '2'],
            ['red bell pepper', '1'],
            ['yellow onion', '1'],
            ['garlic', '3 cloves'],
            ['soy sauce', '1/4 cup'],
            ['brown sugar', '2 tablespoons'],
            ['cornstarch', '2 teaspoons'],
            ['sesame oil', '2 tablespoons'],
            ['vegetable oil', '2 tablespoons']
        ],
        instructions: [
            'Rinse the rice in a strainer and let it soak in water for 30 minutes.',
            'In a small bowl, whisk together soy sauce, brown sugar, cornstarch, and 1/4 cup of water to make the sauce.',
            'Cut broccoli into small florets, slice carrots, red bell pepper, and yellow onion into thin strips.',
            'Heat vegetable oil and sesame oil in a large skillet over medium-high heat. Add minced garlic and cook until fragrant, about 1 minute.',
            'Add vegetables to the skillet and stir-fry for 5-7 minutes, until the vegetables are tender but still crisp.',
            'Pour the sauce into the skillet and stir to combine. Cook for 1-2 minutes until the sauce thickens.',
            'Serve the vegetable stir-fry over cooked rice.'
        ],
        image_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2008/01/Vegetable-stir-fry-b669c05.jpg?quality=90&webp=true&resize=440,400'
    },
    {
        recipeID: 23,
        recipeName: 'Spaghetti Carbonara',
        serving: 4,
        ingredients: [
            ['spaghetti', '12 ounces'],
            ['pancetta', '4 ounces'],
            ['Parmesan cheese', '1 cup'],
            ['eggs', '2'],
            ['garlic', '3 cloves'],
            ['butter', '2 tablespoons'],
            ['olive oil', '2 tablespoons'],
            ['salt', '1 teaspoon'],
            ['black pepper', '1/2 teaspoon'],
            ['fresh parsley', 'for garnish']
        ],
        instructions: [
            'Cook spaghetti according to package instructions.',
            'Dice pancetta and cook in a large skillet over medium heat until crispy. Remove pancetta from the skillet and set aside.',
            'Mince garlic and cook in the same skillet with the pancetta fat until fragrant, about 1 minute.',
            'In a small bowl, whisk together eggs, Parmesan cheese, salt, and black pepper.',
            'Add cooked spaghetti to the skillet and toss with pancetta and garlic.',
            'Remove the skillet from heat and add egg mixture. Toss quickly to coat the spaghetti with the egg mixture.',
            'Garnish with fresh parsley and serve.'
        ],
        image_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-1001491_11-2e0fa5c.jpg?quality=90&webp=true&resize=440,400'
    },
    {
        recipeID: 24,
        recipeName: 'Honey Garlic Shrimp',
        serving: 4,
        ingredients: [
        ['shrimp', '1 pound'],
        ['honey', '1/4 cup'],
        ['soy sauce', '1/4 cup'],
        ['garlic', '3 cloves'],
        ['cornstarch', '1 tablespoon'],
        ['water', '1 tablespoon'],
        ['green onions', 'for garnish']
        ],
        instructions: [
        'Peel and devein the shrimp.',
        'In a large skillet over medium heat, add shrimp and cook for 2-3 minutes on each side until pink and cooked through.',
        'Add garlic to the skillet and cook for 30 seconds, stirring constantly.',
        'In a small bowl, whisk together cornstarch and water. Pour the mixture into the skillet and stir until the sauce thickens.',
        'Garnish with sliced green onions and serve over rice or noodles.'
      ],
      image_link: 'https://www.eatwell101.com/wp-content/uploads/2021/01/healthy-honey-garlic-shrimp-recipe.jpg'
    },
]


export { recipe_data };
